config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root 'static_pages#home'

  get 'weixin', to: 'weixin#validate'
  get 'gallery', to: 'weixin#index'
  resources :weixin, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:wechat]
end

app/models/weixin.rb
class Weixin < ActiveRecord::Base
  attr_reader :image_remote_url
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def avatar_remote_url=(url_value)
    self.image = URI.parse(url_value)
    @image_remote_url = url_value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/weixin_controller.rb
class WeixinController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :get_token, only: [:create]
  def index
    @gallery = Weixin.all
  end

  def create
    # if params[:xml][:MsgType] == "text"
    #   render "text", layout: false, format: :xml
    # end
    get_token
    case params[:xml][:MsgType]
      when "event"
        if params[:xml][:Event] == "subscribe"
          render "subscribe", layout: false, format: :xml
        end
      when "text"
        render "text", layout: false, formats: :xml
      when "image"
        @image_remote_url = Weixin.new
        image_url = params[:xml][:PicUrl]
        @image_remote_url.avatar_remote_url= image_url
        @image_remote_url.save
        render "echo", layout: false, formats: :xml
      else
    end
  end

  def validate
    render text: params[:echostr]
  end

  private
  def validate_wechat
    array = [Rails.configuration.weixin_token, params[:timestamp], params[:nonce]].sort
    if params[:signature] != Digest::SHA1.hexdigest(array.join)
      render text: "Forbidden", :status => 403
    end
  end

  def get_token
    require 'net/http'
    url = URI('https://api.weixin.qq.com/cgi-bin/token')
    params = { grant_type: "client_credential", appid: "wx90ad430687fadcae", secret: "ab64cf9a1f562f6df22c845a071f50af" }
    url.query = URI.encode_www_form(params)

    res = Net::HTTP.get_response(url)
    puts res.body if res.is_a?(Net::HTTPSuccess)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/wechat_helper.rb
module WechatHelper
end

app/helpers/weixin_helper.rb
module WeixinHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wechat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1 class="page-header text-center text-uppercase">Scan QR</h1>
<div class="jumbotron text-center">
  <%= image_tag 'qr.jpg', style: 'display:block;margin: 0 auto;' %>
  <%= link_to 'Check Gallery', gallery_path %>
</div>

app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/weixin/echo.xml.erb
<xml>
    <ToUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></ToUserName>
    <FromUserName><![CDATA[<%= params[:xml][:ToUserName] %>]]></FromUserName>
    <CreateTime><%= Time.now.to_i %></CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content>
      <![CDATA[wechat-test：<%= params[:xml][:Content] %>
        <% if params[:xml][:PicUrl].present? %>
          PicUrl: <%= params[:xml][:PicUrl] %>
          MediaId: <%= params[:xml][:MediaId] %>
        <% end %>
      ]]>
      </Content>
    <FuncFlag>0</FuncFlag>
</xml>

app/views/weixin/index.html.erb
<div class="waterfall">
  <% @gallery.each do |gallery| %>
    <%= image_tag gallery.image.url(:original), style: 'float:left;margin: 10px' %>
  <% end %>
</div>

app/views/weixin/subscribe.xml.erb
<xml>
    <ToUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></ToUserName>
    <FromUserName><![CDATA[<%= params[:xml][:ToUserName] %>]]></FromUserName>
    <CreateTime><%= Time.now.to_i %></CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content>
      <![CDATA[wechat-test：Thank you for subscribing]]>
    </Content>
</xml>

app/views/weixin/text.xml.erb
<xml>
    <ToUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></ToUserName>
    <FromUserName><![CDATA[<%= params[:xml][:ToUserName] %>]]></FromUserName>
    <CreateTime><%= Time.now.to_i %></CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content>
      <![CDATA[wechat-test：Hello]]>
      </Content>
    <FuncFlag>0</FuncFlag>
</xml>